// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MauiTemplates
{
    internal sealed partial class Vsix
    {
        public const string Id = "MauiTemplates.20dca96a-7311-401f-84ed-980478fb319b";
        public const string Name = ".NET MAUI Project and Item Templates";
        public const string Description = @".NET MAUI Project, Item Templates, and Code Snippets for Visual Studio 2022 (.NET MAUI RC2).";
        public const string Language = "en-US";
        public const string Version = "1.4.1.0";
        public const string Author = "Vijay Anand E G";
        public const string Tags = "MAUI, iOS, Android, macOS, WinUI, Windows, Desktop, Mobile, Blazor, WinUI, .NET MAUI, Mac Catalyst, Templates, VS2022, Visual Studio, WinUI3, RC2, Code Snippets, Unified, All-in-One, Hybrid, Tizen";
    }
}
