// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VijayAnand.MauiTemplates
{
    internal sealed partial class Vsix
    {
        public const string Id = "MauiTemplates.20dca96a-7311-401f-84ed-980478fb319b";
        public const string Name = ".NET MAUI Project and Item Templates";
        public const string Description = @".NET MAUI Project, Item Templates, and Code Snippets for Visual Studio 2022 and 2026 Insiders (.NET MAUI 8, 9, and 10 Previews).";
        public const string Language = "en-US";
        public const string Version = "7.9.1.0";
        public const string Author = "Vijay Anand E G";
        public const string Tags = "MAUI, iOS, Android, macOS, WinUI, Windows, Desktop, Mobile, Blazor, .NET MAUI, Mac Catalyst, Templates, VS2022, Visual Studio, WinUI3, GA, Code Snippets, Unified, All-in-One, Hybrid, Tizen, Stable, Blazor Hybrid, BlazorWebView, C#, Handlers, Maps, MAUI Maps, MVVM, XAML, SR, WinUI, Service Release, Dual Screen, Foldable, Surface Duo, General Availability, Markup, Fluent, C# Markup, Media, Audio, Video, Playback, Streaming, AV, Class, .NET 8, Razor, Reactor, Compiled, Bindings, MVU, F#, Fabulous, Generic, .NET 9, CPM, NuGet, Camera, ARM64, JavaScript, JS, HybridWebView, .NET 10, Preview, VS2026, Insiders";
    }
}
